# Database
MYSQL_USERNAME: spring
MYSQL_PASSWORD: spring1234
MYSQL_HOST: localhost
MYSQL_PORT: 3308
MYSQL_DATABASE: secureBD

# Server Config
CONTAINER_PORT: 8085
ACTIVE_PROFILE: test

# Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: temgouaromeo258@gmail.com
EMAIL_PASSWORD: tjss ehul xmjt imxj
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200

JWT_SECRET: Wilson82629274*


